version: "3"

services:
  example:
    container_name: example
    ports:
      - 4000:4000
    build: ./backend
# build:
  #      context: ./backend

  mongodb:
    image: mongo
    container_name: db_GrabYourbags
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  database_web:
    image: mongo-express
    container_name: db_GYB
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
    depends_on:
      - mongodb